### PR TITLE
Fix Crash with Air Item: java.lang.ClassCastException: class net.minecraft.class_2189 cannot be cast to class net.minecraft.class_2480 

### PR DESCRIPTION
**Pull request by SteveKunG**
I encounter this issue when I transfer items from a chest to my inventory (with MouseWheelie mod) by drag mouse quickly.
To solve this I added an Air item check before return a Shulker Box color.
Hopefully it fixes this problem, please tell me if I'm doing something wrong. Thanks!

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 4/30/22, 8:12 PM
Description: Rendering screen

java.lang.ClassCastException: class net.minecraft.class_2189 cannot be cast to class net.minecraft.class_2480 (net.minecraft.class_2189 and net.minecraft.class_2480 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @2a76840c)
	at com.misterpemodder.shulkerboxtooltip.impl.provider.ShulkerBoxPreviewProvider.getWindowColor(ShulkerBoxPreviewProvider.java:35)
	at com.misterpemodder.shulkerboxtooltip.impl.renderer.ModPreviewRenderer.setColor(ModPreviewRenderer.java:52)
	at com.misterpemodder.shulkerboxtooltip.impl.renderer.ModPreviewRenderer.drawBackground(ModPreviewRenderer.java:95)
	at com.misterpemodder.shulkerboxtooltip.impl.renderer.ModPreviewRenderer.draw(ModPreviewRenderer.java:152)
	at com.misterpemodder.shulkerboxtooltip.impl.tooltip.PreviewTooltipComponent.drawItems(PreviewTooltipComponent.java:65)
	at net.minecraft.class_437.redirect$bmh000$drawPosAwareComponent(class_437.java:3735)
	at net.minecraft.class_437.method_32633(class_437.java:283)
	at net.minecraft.class_437.method_32634(class_437.java:179)
	at net.minecraft.class_437.method_25409(class_437.java:170)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_490.method_25394(class_490.java:94)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.misterpemodder.shulkerboxtooltip.impl.provider.ShulkerBoxPreviewProvider.getWindowColor(ShulkerBoxPreviewProvider.java:35)
	at com.misterpemodder.shulkerboxtooltip.impl.renderer.ModPreviewRenderer.setColor(ModPreviewRenderer.java:52)
	at com.misterpemodder.shulkerboxtooltip.impl.renderer.ModPreviewRenderer.drawBackground(ModPreviewRenderer.java:95)
	at com.misterpemodder.shulkerboxtooltip.impl.renderer.ModPreviewRenderer.draw(ModPreviewRenderer.java:152)
	at com.misterpemodder.shulkerboxtooltip.impl.tooltip.PreviewTooltipComponent.drawItems(PreviewTooltipComponent.java:65)
	at net.minecraft.class_437.redirect$bmh000$drawPosAwareComponent(class_437.java:3735)
	at net.minecraft.class_437.method_32633(class_437.java:283)
	at net.minecraft.class_437.method_32634(class_437.java:179)
	at net.minecraft.class_437.method_25409(class_437.java:170)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_490.method_25394(class_490.java:94)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (392, 242). Absolute: (1177.000000, 726.000000)
	Screen size: Scaled: (640, 343). Absolute: (1920, 1027). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['SteveKunG'/195480, l='ClientLevel', x=30.70, y=61.00, z=195.49]]
	Chunk stats: 4096, 1985 F: 2240 L: 0 U: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,67,177), Section: (at 0,3,1 in 4,4,11; chunk contains blocks 64,-64,176 to 79,319,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 473033228 game time, 498455306 day time
	Server brand: iSMP - Fabric 1.18.2
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, vanilla_fixes, clearlance.zip, glass_sound_fix_1.17+.zip, minventory.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1068136136 bytes (1018 MiB) / 2248146944 bytes (2144 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 47825.90
	Virtual memory used (MB): 13300.21
	Swap memory total (MB): 15104.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		amecsapi: Amecs API 1.3.6+mc22w06a
		architectury: Architectury 4.2.50
		betterbeds: Better Beds 1.3.0
		bobby: Bobby 3.1.1
		boostedbrightness: Boosted Brightness 2.1.1
		borderlessmining: Borderless Mining 1.1.2+1.18.2
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		coat: Coat 1.0.0-beta.17+mc1.18.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.2
		com_udojava_evalex: EvalEx 2.7
		continuity: Continuity 1.1.0+1.18.2
		craftpresence: CraftPresence 1.8.8
		enhancedblockentities: Enhanced Block Entities 0.6+1.18.2
		fabric: Fabric API 0.51.1+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.13.3
		fabulousclouds: Fabulous Clouds 0.3.0
		fallingleaves: Falling Leaves 1.10.0+1.18.2
		indicatia: Indicatia 6.1.0
		indium: Indium 1.0.3+mc1.18.2
		io_leangen_geantyref_geantyref: geantyref 1.3.13
		ismputils: iSMPUtils 2.0.1
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.2
		lightoverlay: Light Overlay 6.0.5
		litematica: Litematica 0.11.2
		lithium: Lithium 0.7.10-SNAPSHOT
		malilib: MaLiLib 0.12.1
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.2.1
		mousewheelie: Mouse Wheelie 1.8.8+mc1.18.2
		no_fog: No Fog 1.2.2+1.16.5-1.18.2
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		replayfov: ReplayFov 1.0
		replaymod: Replay Mod 1.18.2-2.6.4
		servertick: Server Tick 1.6
		sheepconsistency: Sheep Consistency 1.0.4
		shulkerboxtooltip: Shulker Box Tooltip 3.0.7+1.18.2
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+replaymod.unknown
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.2+fabric.89b8d9f
		tooltipfix: ToolTip Fix 1.0.4-1.18
		tweakeroo: Tweakeroo 0.13.1
		tweed4_annotated: tweed4_annotated 1.3.0+mc1.18.2
		tweed4_base: tweed4_base 1.5.0+mc1.18.2
		tweed4_data: tweed4_data 1.2.1+mc1.18.2
		tweed4_data_hjson: tweed4_data_hjson 1.1.0+mc1.18.2
		tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		voicechat: Simple Voice Chat 1.18.2-2.2.37
		worldedit: WorldEdit 7.2.10+1742f98
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.29, NVIDIA Corporation
	Window size: 1920x1027
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, file/vanilla_fixes, file/clearlance.zip, file/glass_sound_fix_1.17+.zip, file/minventory.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
```

### CODE REVIEW

**Comment by MisterPeModder** [comment]
Thank you for contributing!

Although this would fix your particular issue with the shulker preview, I am worried this crash would occur with most `PreviewProvider` implementations (including third-party ones).

Normally `PreviewProvider` should be able to safely assume that the `ItemStack` corresponds to its type, since they are registered in the `PreviewProviderRegistry` with specific items.

I haven't tried to reproduce the issue yet, but I suspect this is due to MouseWheelie or some other mod modifying the item stack that is passed to the `PreviewContext`.

Maybe we can fix the issue by calling ItemStack.copy() when creating the context at https://github.com/MisterPeModder/ShulkerBoxTooltip/blob/6a6ecefbe93832d2184c58e8a8388428999f9b8a/src/main/java/com/misterpemodder/shulkerboxtooltip/mixin/client/ItemStackMixin.java#L32=?

**Comment by CompaqDisc** [comment]
I have opened an issue for this with reproduction steps in #82

**Comment by CompaqDisc** [comment]
:facepalm: And it looks like I completely missed the fact that https://github.com/MisterPeModder/ShulkerBoxTooltip/commit/f68a71516b791eebf61a98302ece4eeffb032ce2 exists...
That seems to have worked like a charm! Unfortunately 3.0.8 ~~doesn't seem to be on your CurseForge page yet~~ is an Alpha on your CurseForge page and I completely missed it.

**Comment by SteveKunG** [comment]
Thank you for fixing this! I wasn't looking deep enough into the code.
Tested with Mouse Wheelie is working perfectly fine.

**Pull request closed without merging**
