### PR TITLE
Update to 1.21

### PR DESCRIPTION
**Pull request by MATRIX-feather**
Simply tested with fabric and neoforge, both works :)

### CODE REVIEW

**Comment by ThisCatLikesCrypto** [comment]
[shulkerboxtooltip-fabric-4.1.0-alpha.4+1.21.zip](https://github.com/user-attachments/files/15874842/shulkerboxtooltip-fabric-4.1.0-alpha.4%2B1.21.zip)

Here's the built jar for fabric :)

**Comment by venaminecraft** [comment]
Thank you!

**Comment by MisterPeModder** [comment]
Thank you for your help. I was quite busy the last few weeks, but a build for 1.20.6 and 1.21 should be ready in the next few hours for Fabric, NeoForge *and* Forge (I had to rewrite the config system from scratch for that).

**Comment by MisterPeModder** [comment]
Turns out 1.20.6+ Forge is not supported by Architectury *at all*.
The config rewrite was not necessary after all... oh well \_(ツ)_/¯

**Pull request closed without merging**
